# Generated by Django 5.1.4 on 2025-01-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitcompletion',
            name='status',
            field=models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('COMPLETE', 'Complete'), ('N/A', 'N/A')], default='INCOMPLETE', max_length=20),
        ),
    ]
