# Generated by Django 5.1.4 on 2025-01-30 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0002_habitcompletion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 12, 30)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='habit',
            unique_together={('name', 'start_date', 'end_date')},
        ),
    ]
