# Generated by Django 5.1.4 on 2025-02-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0003_habit_end_date_habit_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitcompletion',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
