# Generated by Django 5.1.4 on 2025-02-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyquote',
            name='last_used',
            field=models.DateField(blank=True, null=True),
        ),
    ]
